### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jli113** [RenqiChen/Social_Science#12]
```
Traceback (most recent call last):
  File "/home/k1/Social_Science/sci_platform/run.py", line 81, in <module>
    platform_example.running(args.epochs)
  File "/home/k1/Social_Science/sci_platform/sci_platform.py", line 401, in running
    self.team_pool[leader_index][team_index].action_excution(self)
  File "/home/k1/Social_Science/sci_platform/sci_team/SciTeam.py", line 92, in action_excution
    action(platform)
  File "/home/k1/Social_Science/sci_platform/sci_team/SciTeam.py", line 308, in generate_idea
    idea_key = old_idea.split("Idea")[1]
               ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
Tried llama3.1:8b, qwen2.5:14b, gemma2:27b, mistral-small for the agent model

Based on my experiences with AI_scientist, This relates to the model's performance.

**Comment by RenqiChen** [comment]
Yes. In the current open-source code, we have not considered the use of try...except... statements. In the near future, we will release a more refined version of the code.

**Comment by jli113** [comment]
May I ask about your hardware?

**Comment by RenqiChen** [comment]
We use an A100 (40G).

**Comment by jli113** [comment]
I see, I'm using a 4070ts. When running with llama3.3:70b, the process could finish. Poor devices need larger models for precision, really **The More You Buy, The More You Save**.
