### ISSUE TITLE
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by jli113** [RenqiChen/Social_Science#14]
Traceback (most recent call last):
  File "/home/k1/Social_Science/sci_platform/run.py", line 72, in <module>
    platform_example.running(args.epochs)
  File "/home/k1/Social_Science/sci_platform/sci_platform.py", line 400, in running
    self.team_pool[leader_index][team_index].action_excution(self)
  File "/home/k1/Social_Science/sci_platform/sci_team/SciTeam.py", line 92, in action_excution
    action(platform)
  File "/home/k1/Social_Science/sci_platform/sci_team/SciTeam.py", line 549, in generate_abstract
    if metric[split_keyword]>=70:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

**Comment by RenqiChen** [comment]
Hello, it is also caused by the format of the LLM output.
